1. Carga de librerías y datos

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/smoking_prediction.csv")

df.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,3.38,0.04,0.04,0.04,0.04,...,0.51,0.04,0.00,0.75,0.79,1.13,Y,0,Y,0
1,1,F,40,160,60,3.38,0.01,0.00,0.04,0.04,...,0.50,0.04,0.00,0.92,0.79,0.75,Y,0,Y,0
2,2,M,55,170,60,3.33,0.01,0.01,0.04,0.04,...,0.63,0.04,0.04,0.88,0.67,0.92,Y,0,N,1
3,3,M,40,165,70,3.67,0.05,0.05,0.04,0.04,...,0.59,0.04,0.04,0.79,1.08,0.75,Y,0,Y,0
4,4,F,40,155,60,3.58,0.04,0.04,0.04,0.04,...,0.50,0.04,0.00,0.67,0.58,0.92,Y,0,N,0

2. Copia de trabajo

In [2]:
df_prep = df.copy()

3. Eliminación de variables no útiles

In [3]:
df_prep = df_prep.drop(columns=["ID", "oral"])

df_prep.columns

Index(['gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)',
       'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)',
       'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol',
       'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein',
       'serum creatinine', 'AST', 'ALT', 'Gtp', 'dental caries', 'tartar',
       'smoking'],
      dtype='object')

4. Codificación de variables categóricas

In [4]:
#Pasamos gender y tartar a numéricas

df_prep["gender"] = df_prep["gender"].map({
    "F": 0,
    "M": 1
})

df_prep["tartar"] = df_prep["tartar"].map({
    "N": 0,
    "Y": 1
})

df_prep[["gender", "tartar"]].head()

   gender  tartar
0       0       1
1       0       1
2       1       0
3       1       1
4       0       0

5. Verificación de tipos

In [5]:
df_prep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               50000 non-null  int64
 1   age                  50000 non-null  int64
 2   height(cm)           50000 non-null  int64
 3   weight(kg)           50000 non-null  int64
 4   waist(cm)            50000 non-null  float64
 5   eyesight(left)       50000 non-null  float64
 6   eyesight(right)      50000 non-null  float64
 7   hearing(left)        50000 non-null  float64
 8   hearing(right)       50000 non-null  float64
 9   systolic             50000 non-null  float64
 10  relaxation           50000 non-null  float64
 11  fasting blood sugar  50000 non-null  float64
 12  Cholesterol          50000 non-null  float64
 13  triglyceride         50000 non-null  float64
 14  HDL                  50000 non-null  float64
 15  LDL                  50000 non-null  float64
 16  hemoglobin           50000 non-null  float64
 17  Urine protein        50000 non-null  float64
 18  serum creatinine     50000 non-null  float64
 19  AST                  50000 non-null  float64
 20  ALT                  50000 non-null  float64
 21  Gtp                  50000 non-null  float64
 22  dental caries        50000 non-null  int64
 23  tartar               50000 non-null  int64
 24  smoking              50000 non-null  int64
dtypes: float64(18), int64(7)
memory usage: 9.5 MB

6. Separación de variables predictoras y target

In [6]:
X = df_prep.drop(columns=["smoking"])

y = df_prep["smoking"]

print(X.shape)
print(y.shape)

(50000, 24)
(50000,)

7. División Train/Test

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#¿Por qué stratify=y? Porque vimos que: 63% no fumadores 37% fumadores
#y queremos conservar esa proporción tanto en entrenamiento como en validación.

In [8]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

smoking
0    0.633425
1    0.366575
Name: proportion, dtype: float64
smoking
0    0.6334
1    0.3666
Name: proportion, dtype: float64

Se realizó una partición estratificada de los datos, destinando el 80% para entrenamiento y el 20% para validación. La estratificación permitió conservar la distribución original de la variable objetivo en ambos conjuntos, garantizando una evaluación representativa del desempeño de los modelos.

8. Guardado opcional

In [9]:
df_prep.to_csv(
    "../data/processed/smoking_prediction_preprocessed.csv",
    index=False
)